src/app/models/agencia.models.ts, src/app/models/buques.models.ts, src/app/models/camion.models.ts
=> Angel prueba

package-lock.json, src/app/pages/agencias/agencia.component.html, src/app/pages/agencias/agencia.component.ts, src/app/pages/agencias/agencias.component.html, src/app/pages/agencias/agencias.component.ts, src/app/pages/clientes/cliente.component.ts, src/app/pages/empresa/empresa.component.ts, src/app/pages/maniobras/maniobra.component.ts, src/app/pages/transportistas/transportista.component.ts, src/app/pages/transportistas/transportistas.component.html, src/app/services/agencia/agencia.service.ts, src/app/services/interceptors/token-interceptor.service.ts, src/app/services/transportista/transportista.service.ts
Catalogo de agencia terminado, los archivos que no son de agencia se modificaron para hacer referencia a los métodos que se cambio de nombre a get.
=> Cambios catalogo agencia y varios

src/app/models/maniobras.models.ts, src/app/pages/maniobras/maniobra.service.ts, src/app/pages/maniobras/vacios.component.html, src/app/pages/maniobras/vacios.component.ts, src/app/pages/operadores/operador.component.ts, src/app/pages/pages.module.ts, src/app/pages/pages.routes.ts, src/app/pages/viajes/viaje.models.ts, src/app/pages/viajes/viaje.service.ts
* agregar columna FacturaManiobra
* Modificar modelo de back en maniobras
* agrego checkbox y boton de asignar factura (string)
* filtrar solo no facturados y viaje
* revisar operadores no se muestra su foto
=> Vacios y Fotos de Operadores

src/app/pages/maniobras/maniobra.service.ts, src/app/pages/maniobras/transito_entrada/espera.component.html, src/app/pages/maniobras/transito_entrada/espera.component.ts, src/app/pages/maniobras/transito_entrada/llegada_entrada.component.html, src/app/pages/maniobras/transito_entrada/llegada_entrada.component.ts, src/app/pages/maniobras/transito_entrada/transito.component.html, src/app/pages/maniobras/transito_entrada/transito.component.ts, src/app/pages/pages.module.ts, src/app/pages/pages.routes.ts, src/app/pages/solicitudes/carga/solicitudes_carga.component.ts, src/app/pages/solicitudes/descarga/solicitud_descarga.component.html, src/app/pages/solicitudes/descarga/solicitud_descarga.component.ts, src/app/pages/solicitudes/descarga/solicitudes_descarga.component.html, src/app/pages/solicitudes/descarga/solicitudes_descarga.component.ts, src/app/pages/solicitudes/solicitud.service.ts, src/app/pages/solicitudes/solicitudD_aprobar.component.html, src/app/pages/solicitudes/solicitudD_aprobar.component.ts, src/app/pages/solicitudes/solicitudesAprobaciones.component.html, src/app/pages/solicitudes/solicitudesAprobaciones.component.ts, src/app/pages/solicitudes/transportista/solicitud_reasigna_transportista.component.html, src/app/pages/solicitudes/transportista/solicitud_reasigna_transportista.component.ts, src/app/pages/solicitudes/transportista/solicitud_transportista.component.html, src/app/pages/solicitudes/transportista/solicitud_transportista.component.ts, src/app/pages/solicitudes/transportista/solicitudes_transportista.component.html, src/app/pages/solicitudes/transportista/solicitudes_transportista.component.ts
Se valido las solicitudes de descarga.
Se hizo la página de transportistas - solicitudes
Se hizo la página de transportistas - asignación de chófer y camión-.
Se hizo la página de transportista - reasignacion de transportista
=> Solicitudes4.0

src/app/pages/contenedores-lr/contenedores-lr.component.html, src/app/pages/contenedores-lr/contenedores-lr.component.ts, src/app/pages/fotos/fotos.component.ts, src/app/pages/maniobras/lavadoreparacion_terminar/lavado_reparacion.component.html, src/app/pages/maniobras/maniobra.service.ts, src/app/pages/maniobras/revision_revisa/revisa.component.html, src/app/pages/maniobras/revision_revisa/revision.component.html, src/app/pages/maniobras/transito_entrada/espera.component.html, src/app/pages/maniobras/transito_entrada/transito.component.html, src/app/pages/pages.routes.ts, src/app/pages/solicitudes/aprobar_descarga.component.html, src/app/pages/solicitudes/aprobar_descarga.component.ts, src/app/pages/solicitudes/descarga/solicitud_descarga.component.ts, src/app/pages/solicitudes/solicitud.service.ts, src/app/pages/viajes/viaje.service.ts, src/app/services/buque/buque.service.ts
Se agredo la solicitud de contenedores woodgenix..
Se reviso las etapas..
=> SOL.WOODGENIEX

src/app/config/config.ts, src/app/pages/maniobras/maniobras.component.html, src/app/pages/maniobras/maniobras.component.ts, src/app/pages/operadores/operador.component.html, src/app/pages/transportistas/transportista.component.html, src/app/shared/sidebar/sidebar.component.ts
Se agregaron columnas de lavado y fotos de reparaciones también se modifico el Ed de Operador para que en vez de imagen se agregue un PDF de la licencia.
=> Cambios varios

src/app/pages/fotos/fotos.component.html, src/app/pages/maniobras/5inventario/inventario.component.html, src/app/pages/maniobras/5inventario/inventario.component.ts, src/app/pages/solicitudes/transportista/solicitudes_transportista.component.html
Se cambio el color de boton fotos y tamaño de tablas
=> cambio de colores y tablas 

src/app/pages/maniobras/maniobras.component.html
se agregaron los tabs restantes
=> tabs restantes 

src/app/pages/maniobras/facturacion-maniobras/facturacion-maniobras.component.html, src/app/pages/maniobras/vacios.component.html
Termino cambios del ojito (Boton corregir de facturacion maniobras y facturacion vacios)
=> Termino cambios del ojito

src/app/pages/maniobras/maniobras.component.ts
=> cambios de flltro

src/app/pages/contenedores-lr/contenedores-lr.component.html, src/app/pages/contenedores-lr/contenedores-lr.component.ts, src/app/pages/maniobras/maniobra.service.ts, src/app/pages/usuarios/usuario.service.ts
Se  separo el catalogo de lavado y reparación
=> Lavado y Reparacion 

src/app/pages/solicitudes/carga/solicitud_carga.component.ts, src/app/pages/solicitudes/descarga/solicitud_descarga.component.ts
Se agrego la validación de agencias por role
=> validacion de agencias

src/app/login/login.component.html, src/app/pages/buques/paginator-español.ts, src/app/pages/usuarios/usuario.service.ts, src/app/pages/usuarios/usuarios.component.html, src/app/pages/usuarios/usuarios.component.ts
=> cambios_020110_R

src/app/pages/maniobras/2revisar/revisar.component.ts, src/app/pages/solicitudes/carga/solicitud_carga.component.html, src/app/pages/solicitudes/carga/solicitud_carga.component.ts
=> termino cantidad

src/app/pages/maniobras/3terminar_lavado_reparacion/termina_lavado_reparacion.component.ts
=> CAMBIO_L/R

src/app/pages/maniobras/maniobras.component.ts, src/app/pages/solicitudes/aprobar_descarga.component.ts
Se corrijo el filtrado de maniobras
=> Filtrado de maniobras

src/app/pages/maniobras/facturacion-maniobras/facturacion-maniobras.component.html, src/app/pages/maniobras/facturacion-maniobras/facturacion-maniobras.component.ts, src/app/pages/maniobras/maniobras-diario/maniobras-diario.component.html, src/app/pages/maniobras/maniobras-diario/maniobras-diario.component.ts, src/app/pages/maniobras/maniobras.component.html, src/app/pages/maniobras/maniobras.component.ts, src/app/pages/maniobras/vacios.component.html, src/app/pages/maniobras/vacios.component.ts, src/app/services/excel/excel.service.ts
termino corrección de excel de maniobras 29/01/2020
=> termino corrección de excel de maniobras 29/01/2020 master

src/app/pages/maniobras/facturacion-maniobras/facturacion-maniobras.component.html, src/app/pages/maniobras/facturacion-maniobras/facturacion-maniobras.component.ts, src/app/pages/maniobras/maniobras-diario/maniobras-diario.component.html, src/app/pages/maniobras/maniobras-diario/maniobras-diario.component.ts, src/app/pages/maniobras/maniobras.component.html, src/app/pages/maniobras/vacios.component.html, src/app/pages/maniobras/vacios.component.ts, src/app/services/excel/excel.service.ts
termino corrección de excel de maniobras 29/01/2020
=> termino corrección de excel de maniobras 29/01/2020

src/app/config/config.ts, src/app/login/login.component.html, src/app/login/login.component.ts, src/app/pages/solicitudes/aprobaciones.component.html
=> termino resset_password

src/app/models/maniobra.models.ts, src/app/pages/maniobras/4x_cargar/carga_contenedor.component.html, src/app/pages/maniobras/4x_cargar/carga_contenedor.component.ts, src/app/pages/usuarios/usuarios.component.html
temino contenedores por cargar naviera
=> temino contenedores por cargar naviera

src/app/pages/maniobras/4x_cargar/carga_contenedor.component.html, src/app/pages/maniobras/4x_cargar/carga_contenedor.component.ts, src/app/pages/solicitudes/aprobaciones.component.ts
=> termino corrección por cargar

src/app/pages/solicitudes/aprobaciones.component.html, src/app/pages/solicitudes/solicitud.service.ts, src/app/pages/viajes/viaje.component.ts, src/app/pages/viajes/viaje.service.ts
se corrige viaje y conflictos de solicitud
=> se corrige viaje y conflictos de solicitud

src/app/app.module.ts, src/app/dialogs/info-dialog/info-dialog.component.css, src/app/dialogs/info-dialog/info-dialog.component.html, src/app/dialogs/info-dialog/info-dialog.component.ts, src/app/pages/pages.module.ts, src/app/pages/solicitudes/aprobar_carga.component.html, src/app/pages/solicitudes/aprobar_carga.component.ts, src/app/pages/solicitudes/aprobar_descarga.component.html, src/app/pages/solicitudes/aprobar_descarga.component.ts
=> termino botón de dialog

src/app/pages/maniobras/maniobras-diario/maniobras-diario.component.html, src/app/pages/solicitudes/descarga/solicitud_descarga.component.html, src/app/pages/solicitudes/transportista/solicitud_transportista.component.html, src/app/pages/solicitudes/transportista/solicitud_transportista.component.ts, src/app/pages/solicitudes/transportista/solicitudes_transportista.component.html
TERMINO BOTONES DE ED TRANSPORTISTA
=> TERMINO BOTONES DE ED TRANSPORTISTA

src/app/pages/pages.routes.ts
=> termino menu

src/app/pages/camiones/camion.component.ts, src/app/pages/solicitudes/solicitudes.component.html
termino transportista y tabla solicitud
=> termino transportista y tabla solicitud

src/app/pages/solicitudes/descarga/solicitud_descarga.component.ts
=> termino correo descarga

src/app/pages/buques/buque.component.ts, src/app/pages/buques/buques.component.ts, src/app/pages/camiones/camion.component.html, src/app/pages/camiones/camion.component.ts, src/app/pages/camiones/camiones.component.ts, src/app/pages/operadores/operador.component.ts, src/app/pages/operadores/operadores.component.ts
=> termino sockets transportista

src/app/pages/detalle-maniobra/detalle-maniobra.component.html, src/app/pages/maniobras/3terminar_lavado_reparacion/termina_lavado_reparacion.component.html, src/app/pages/maniobras/papeleta/papeleta.component.ts, src/app/pages/solicitudes/aprobaciones.component.ts, src/app/pages/solicitudes/aprobar_carga.component.ts, src/app/pages/solicitudes/aprobar_descarga.component.ts, src/app/pages/solicitudes/solicitud.service.ts, src/app/pages/solicitudes/transportista/solicitudes_transportista.component.ts, src/app/shared/header/header.component.ts
termino socket de transportista
=> termino socket de transportista

src/app/pages/facturacion/clave-productos-servicios/clave-productos-servicio.component.ts, src/app/pages/maniobras/maniobra.service.ts, src/app/pages/pages.module.ts, src/app/pages/pages.routes.ts, src/app/pages/reportes/reportes.component.css, src/app/pages/reportes/reportes.component.html, src/app/pages/reportes/reportes.component.ts, src/app/pages/usuarios/usuario.service.ts
=> TERMINO REPORTES

src/app/pages/clientes/cliente.component.html, src/app/pages/clientes/cliente.component.ts, src/app/pages/facturacion/facturacion.service.ts, src/app/pages/navieras/naviera.component.html, src/app/pages/navieras/naviera.component.ts, src/app/pages/transportistas/transportista.component.html, src/app/pages/transportistas/transportista.component.ts
=> termino campo uso_cfdi

src/app/pages/facturacion/cfdis/cfdi.component.html, src/app/pages/facturacion/cfdis/cfdi.component.ts
=> botones cfdi

src/app/pages/maniobras/facturacion-maniobras/facturacion-maniobras.component.ts
termino filtros factura maniobra
=> termino filtros factura maniobra

src/app/pages/facturacion/cfdis/cfdi.component.html
=> cambio variable

src/app/pages/facturacion/cfdis/cfdis.component.html, src/app/pages/facturacion/pdf-facturacion/pdf-facturacion.component.css, src/app/pages/facturacion/pdf-facturacion/pdf-facturacion.component.html, src/app/pages/facturacion/pdf-facturacion/pdf-facturacion.component.ts, src/app/pages/facturacion/pdf-facturacion/pdf-facturacion.service.ts, src/app/pipes/imagen.pipe.ts
se realizaron modificaciones en la parte de pdf front los cuales se visualiza ya bien los importes decimal
se agrego un boton sin de envio de correo individual, 
falta terminar el envio de correo al timbrar a los clientes,
=> pdf-booket

src/app/pages/facturacion/cfdis/cfdi.component.css, src/app/pages/facturacion/cfdis/cfdi.component.html, src/app/pages/facturacion/cfdis/cfdi.component.ts, src/app/pages/facturacion/models/cfdi.models.ts, src/app/pages/facturacion/pdf-facturacion/pdf-facturacion.component.html
=> termino info adicional

src/app/pages/facturacion/cfdis/cfdi.component.ts, src/app/pages/facturacion/facturacion.service.ts
=> termino borrado

src/app/pages/facturacion/cfdis/cfdi.component.html, src/app/pages/facturacion/cfdis/cfdi.component.ts, src/app/pages/facturacion/facturacion.service.ts
=> falta botones terminar

src/app/pages/facturacion/cfdis/cfdi.component.ts
=> correccion

src/app/pages/facturacion/cfdis/cfdi.component.html, src/app/pages/reportes/reportes.component.html, src/app/pages/reportes/reportes.component.ts
=> correccion de reportes

src/app/pages/facturacion/facturacion.service.ts, src/app/pages/facturacion/notas-de-credito/nota-de-credito.component.ts, src/app/pages/facturacion/pdf-facturacion/pdf-facturacion.component.ts
=> TERMINO CORRECCIÓN
